# Generated by Django 4.2.7 on 2025-11-07 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('achievement_type', models.CharField(choices=[('score', 'Очки'), ('level', 'Уровень'), ('time', 'Время'), ('special', 'Особое')], default='score', max_length=20)),
                ('requirement', models.IntegerField(verbose_name='Требование')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='Иконка')),
                ('points', models.IntegerField(default=10, verbose_name='Очки за достижение')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название уровня')),
                ('level_data', models.TextField(verbose_name='Данные уровня')),
                ('difficulty', models.IntegerField(default=1, verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Уровень игры',
                'verbose_name_plural': 'Уровни игры',
                'ordering': ['difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameSprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('sprite_type', models.CharField(choices=[('player', 'Игрок'), ('enemy', 'Враг'), ('platform', 'Платформа'), ('item', 'Предмет'), ('background', 'Фон'), ('effect', 'Эффект')], max_length=20)),
                ('image', models.ImageField(upload_to='sprites/', verbose_name='Изображение')),
                ('width', models.IntegerField(default=50, verbose_name='Ширина')),
                ('height', models.IntegerField(default=50, verbose_name='Высота')),
                ('animation_frames', models.IntegerField(default=1, verbose_name='Кадры анимации')),
            ],
            options={
                'verbose_name': 'Спрайт',
                'verbose_name_plural': 'Спрайты',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, verbose_name='Общий счет')),
                ('games_played', models.IntegerField(default=0, verbose_name='Игр сыграно')),
                ('best_score', models.IntegerField(default=0, verbose_name='Лучший результат')),
                ('current_level', models.IntegerField(default=1, verbose_name='Текущий уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['-best_score'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Очки')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('game_data', models.JSONField(default=dict, verbose_name='Данные игры')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamelevel')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='game.player')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='game.player')),
            ],
            options={
                'verbose_name': 'Достижение игрока',
                'verbose_name_plural': 'Достижения игроков',
                'unique_together': {('player', 'achievement')},
            },
        ),
    ]
