# Generated by Django 4.2.7 on 2025-11-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesprite',
            name='image',
        ),
        migrations.AddField(
            model_name='gamesprite',
            name='animation_paths',
            field=models.JSONField(blank=True, default=dict, verbose_name='Пути к анимациям'),
        ),
        migrations.CreateModel(
            name='SpriteAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animation_state', models.CharField(max_length=50, verbose_name='Состояние анимации')),
                ('image', models.ImageField(upload_to='sprites/animations/', verbose_name='Изображение анимации')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('sprite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='game.gamesprite', verbose_name='Спрайт')),
            ],
            options={
                'verbose_name': 'Анимация спрайта',
                'verbose_name_plural': 'Анимации спрайтов',
                'ordering': ['sprite', 'animation_state', 'order'],
                'unique_together': {('sprite', 'animation_state')},
            },
        ),
    ]
